<?php

require_once('MyMathClass.php');
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-10 at 22:39:35.
 */
class MyMathClassTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var MyMathClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MyMathClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Data provider for test methods below
     */
    public static function provider() {
        return array(
            array(1, 2, 3),
            array(4, 2, 6),
            array(1, 5, 6)
        );
    }

    /**
     * Testing addValues returns sum of two values
     * @dataProvider provider
     */
    public function testAddValues($a, $b, $sum) {
        $this->assertEquals(
            $sum, $this->object->addValues($a, $b)
        );
    }
}
